/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as AcademiesIndexRouteImport } from './routes/academies.index'
import { Route as AcademiesAcademyIdRouteImport } from './routes/academies.$academyId'
import { Route as ProfilePersonIdRouteImport } from './routes/profile.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesIndexRoute = AcademiesIndexRouteImport.update({
  id: '/academies/',
  path: '/academies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesAcademyIdRoute = AcademiesAcademyIdRouteImport.update({
  id: '/academies/$academyId',
  path: '/academies/$academyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonIdRoute = ProfilePersonIdRouteImport.update({
  id: '/profile/$personId',
  path: '/profile/$personId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/academies/$academyId': typeof AcademiesAcademyIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/academies/': typeof AcademiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/academies/$academyId': typeof AcademiesAcademyIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/academies': typeof AcademiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/academies/$academyId': typeof AcademiesAcademyIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/academies/': typeof AcademiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/login'
    | '/opportunities'
    | '/academies/$academyId'
    | '/profile/$personId'
    | '/academies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/explore'
    | '/login'
    | '/opportunities'
    | '/academies/$academyId'
    | '/profile/$personId'
    | '/academies'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/explore'
    | '/login'
    | '/opportunities'
    | '/academies/$academyId'
    | '/profile/$personId'
    | '/academies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  AcademiesAcademyIdRoute: typeof AcademiesAcademyIdRoute
  ProfilePersonIdRoute: typeof ProfilePersonIdRoute
  AcademiesIndexRoute: typeof AcademiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/': {
      id: '/academies/'
      path: '/academies'
      fullPath: '/academies/'
      preLoaderRoute: typeof AcademiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/$academyId': {
      id: '/academies/$academyId'
      path: '/academies/$academyId'
      fullPath: '/academies/$academyId'
      preLoaderRoute: typeof AcademiesAcademyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$personId': {
      id: '/profile/$personId'
      path: '/profile/$personId'
      fullPath: '/profile/$personId'
      preLoaderRoute: typeof ProfilePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  AcademiesAcademyIdRoute: AcademiesAcademyIdRoute,
  ProfilePersonIdRoute: ProfilePersonIdRoute,
  AcademiesIndexRoute: AcademiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
